version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3400:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s

  migrate:
    image: migrate/migrate
    container_name: migrate_service
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/database/migration:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:${MYSQL_PASSWORD}@tcp(db:3306)/${MYSQL_DATABASE}",
      "up"
    ]
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3400
      MYSQL_USER: root
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data: